[build]
  publish = "out/"

[build.environment]
  # Use only for build cache.
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@sentry/netlify-build-plugin"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "https://gnosis-safe.io"

[[redirects]]
  from = "/test1/*"
  to = "/"
  status = 301
  force = false

[[redirects]]
  from = "/test2/*"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/test3/*"
  to = "/"
  status = 302
  force = false

[[redirects]]
  from = "/test4/*"
  to = "/"
  status = 302
  force = true

[[redirects]]
  from = "/test5/*"
  to = "/"
  status = 200
  force = false

[[redirects]]
  from = "/test6/*"
  to = "/"
  status = 200
  force = true