[build]
  publish = "out/"

[build.environment]
  # Use only for build cache.
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@sentry/netlify-build-plugin"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "https://gnosis-safe.io"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 302
  force = false