sources:
  - name: scheduling
    handler:
      graphql:
        endpoint: '{context.url:https://subgraph-endpoints.superfluid.dev/optimism-mainnet/flow-scheduler}'
        retry: 5
documents:
  - './*.graphql'
codegen:
  namingConvention: change-case-all#pascalCase
  scalars:
    BigInt: string
    Bytes: string
    BigDecimal: string
  maybeValue: T | null | undefined