// AUTO-GENERATED by scripts/generate-clear-macro-abi.mjs — do not edit.
// Source: contracts/src/DashboardClearMacro.sol via the Foundry artifact
// contracts/out/DashboardClearMacro.sol/DashboardClearMacro.json.
// Regenerate with: pnpm contracts:abi

export const dashboardClearMacroAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "host",
        "type": "address",
        "internalType": "contract ISuperfluid"
      },
      {
        "name": "flowScheduler",
        "type": "address",
        "internalType": "contract IFlowScheduler"
      },
      {
        "name": "feeSuperToken",
        "type": "address",
        "internalType": "contract ISuperToken"
      },
      {
        "name": "baseFeeAmount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "feeReceiver",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "baseFee",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "buildBatchOperations",
    "inputs": [
      {
        "name": "host",
        "type": "address",
        "internalType": "contract ISuperfluid"
      },
      {
        "name": "actionParams",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple[]",
        "internalType": "struct ISuperfluid.Operation[]",
        "components": [
          {
            "name": "operationType",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "target",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "data",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "describeApprove",
    "inputs": [
      {
        "name": "lang",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct DashboardClearMacro.ApproveParams",
        "components": [
          {
            "name": "superToken",
            "type": "address",
            "internalType": "contract ISuperToken"
          },
          {
            "name": "spender",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "amount",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "describeCreateFlow",
    "inputs": [
      {
        "name": "lang",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct DashboardClearMacro.CreateFlowParams",
        "components": [
          {
            "name": "superToken",
            "type": "address",
            "internalType": "contract ISuperToken"
          },
          {
            "name": "receiver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "flowRate",
            "type": "int96",
            "internalType": "int96"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "describeDeleteFlow",
    "inputs": [
      {
        "name": "lang",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct DashboardClearMacro.DeleteFlowParams",
        "components": [
          {
            "name": "superToken",
            "type": "address",
            "internalType": "contract ISuperToken"
          },
          {
            "name": "sender",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "receiver",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "describeDeleteFlowSchedule",
    "inputs": [
      {
        "name": "lang",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct DashboardClearMacro.DeleteFlowScheduleParams",
        "components": [
          {
            "name": "superToken",
            "type": "address",
            "internalType": "contract ISuperToken"
          },
          {
            "name": "receiver",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "describeDowngrade",
    "inputs": [
      {
        "name": "lang",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct DashboardClearMacro.DowngradeParams",
        "components": [
          {
            "name": "superToken",
            "type": "address",
            "internalType": "contract ISuperToken"
          },
          {
            "name": "amount",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "describeScheduleFlow",
    "inputs": [
      {
        "name": "lang",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct DashboardClearMacro.ScheduleFlowParams",
        "components": [
          {
            "name": "superToken",
            "type": "address",
            "internalType": "contract ISuperToken"
          },
          {
            "name": "receiver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "startDate",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "flowRate",
            "type": "int96",
            "internalType": "int96"
          },
          {
            "name": "endDate",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "describeTransfer",
    "inputs": [
      {
        "name": "lang",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct DashboardClearMacro.TransferParams",
        "components": [
          {
            "name": "superToken",
            "type": "address",
            "internalType": "contract ISuperToken"
          },
          {
            "name": "receiver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "amount",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "describeUpdateFlow",
    "inputs": [
      {
        "name": "lang",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct DashboardClearMacro.UpdateFlowParams",
        "components": [
          {
            "name": "superToken",
            "type": "address",
            "internalType": "contract ISuperToken"
          },
          {
            "name": "receiver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "flowRate",
            "type": "int96",
            "internalType": "int96"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "describeUpgrade",
    "inputs": [
      {
        "name": "lang",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct DashboardClearMacro.UpgradeParams",
        "components": [
          {
            "name": "superToken",
            "type": "address",
            "internalType": "contract ISuperToken"
          },
          {
            "name": "amount",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "encodeApprove",
    "inputs": [
      {
        "name": "lang",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct DashboardClearMacro.ApproveParams",
        "components": [
          {
            "name": "superToken",
            "type": "address",
            "internalType": "contract ISuperToken"
          },
          {
            "name": "spender",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "amount",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "actionParams",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "encodeCreateFlow",
    "inputs": [
      {
        "name": "lang",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct DashboardClearMacro.CreateFlowParams",
        "components": [
          {
            "name": "superToken",
            "type": "address",
            "internalType": "contract ISuperToken"
          },
          {
            "name": "receiver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "flowRate",
            "type": "int96",
            "internalType": "int96"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "actionParams",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "encodeDeleteFlow",
    "inputs": [
      {
        "name": "lang",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct DashboardClearMacro.DeleteFlowParams",
        "components": [
          {
            "name": "superToken",
            "type": "address",
            "internalType": "contract ISuperToken"
          },
          {
            "name": "sender",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "receiver",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "actionParams",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "encodeDeleteFlowSchedule",
    "inputs": [
      {
        "name": "lang",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct DashboardClearMacro.DeleteFlowScheduleParams",
        "components": [
          {
            "name": "superToken",
            "type": "address",
            "internalType": "contract ISuperToken"
          },
          {
            "name": "receiver",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "actionParams",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "encodeDowngrade",
    "inputs": [
      {
        "name": "lang",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct DashboardClearMacro.DowngradeParams",
        "components": [
          {
            "name": "superToken",
            "type": "address",
            "internalType": "contract ISuperToken"
          },
          {
            "name": "amount",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "actionParams",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "encodeScheduleFlow",
    "inputs": [
      {
        "name": "lang",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct DashboardClearMacro.ScheduleFlowParams",
        "components": [
          {
            "name": "superToken",
            "type": "address",
            "internalType": "contract ISuperToken"
          },
          {
            "name": "receiver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "startDate",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "flowRate",
            "type": "int96",
            "internalType": "int96"
          },
          {
            "name": "endDate",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "actionParams",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "encodeTransfer",
    "inputs": [
      {
        "name": "lang",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct DashboardClearMacro.TransferParams",
        "components": [
          {
            "name": "superToken",
            "type": "address",
            "internalType": "contract ISuperToken"
          },
          {
            "name": "receiver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "amount",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "actionParams",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "encodeUpdateFlow",
    "inputs": [
      {
        "name": "lang",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct DashboardClearMacro.UpdateFlowParams",
        "components": [
          {
            "name": "superToken",
            "type": "address",
            "internalType": "contract ISuperToken"
          },
          {
            "name": "receiver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "flowRate",
            "type": "int96",
            "internalType": "int96"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "actionParams",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "encodeUpgrade",
    "inputs": [
      {
        "name": "lang",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct DashboardClearMacro.UpgradeParams",
        "components": [
          {
            "name": "superToken",
            "type": "address",
            "internalType": "contract ISuperToken"
          },
          {
            "name": "amount",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "actionParams",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "feeToken",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ISuperToken"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getActionStructHash",
    "inputs": [
      {
        "name": "actionParams",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getActionTypeDefinition",
    "inputs": [
      {
        "name": "encodedPayload",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPrimaryTypeName",
    "inputs": [
      {
        "name": "encodedPayload",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "postCheck",
    "inputs": [
      {
        "name": "host",
        "type": "address",
        "internalType": "contract ISuperfluid"
      },
      {
        "name": "actionParams",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "previewRelayFee",
    "inputs": [
      {
        "name": "actionParams",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "feeToken",
        "type": "address",
        "internalType": "contract ISuperToken"
      },
      {
        "name": "feeReceiver",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "currentFee",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "maxFee",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "error",
    "name": "FeeNotRepresentable",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FeeTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidFlowRate",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidPeriod",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidTimeWindow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "StringsInsufficientHexLength",
    "inputs": [
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "length",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownActionId",
    "inputs": [
      {
        "name": "actionId",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnsupportedLanguage",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
