sources:
  - name: vesting
    handler:
      graphql:
        endpoint: '{context.url:https://api.thegraph.com/subgraphs/name/superfluid-finance/automation-v1-goerli}'
        retry: 5
documents:
  - './*.graphql'
codegen:
  namingConvention: change-case-all#pascalCase
  scalars:
    BigInt: string
    Bytes: string
    BigDecimal: string