sources:
  - name: vesting
    handler:
      graphql:
        endpoint: '{context.url:https://api.goldsky.com/api/public/project_clsnd6xsoma5j012qepvucfpp/subgraphs/vesting-v1-optimism-sepolia/1.1.2/gn}'
        retry: 5
documents:
  - './*.graphql'
codegen:
  namingConvention: change-case-all#pascalCase
  scalars:
    BigInt: string
    Bytes: string
    BigDecimal: string
  maybeValue: T | undefined