export type AnalyticsTransactionNames =
  | "Wrap"
  | "Unwrap"
  | "Approve Allowance"
  | "Send Stream"
  | "Modify Stream"
  | "Cancel Stream"
  | "Approve IDA Subscription"
  | "Revoke IDA Subscription"
  | "Create Vesting Schedule"
  | "Delete Vesting Schedule"
  | "Fix Access for Vesting"
  | "Execute Vesting Cliff And Flow"
  | "Execute Vesting End"
  | "Approve Auto-Wrap Allowance"
  | "Enable Auto-Wrap";
