/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/chains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List configured chains
         * @description Enumerate the configured chains from docs/chain-configs.json for client dropdowns and validation.
         */
        get: {
            parameters: {
                query?: {
                    network?: "mainnet" | "testnet" | "all";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Configured chains, filtered by `network` (defaults to mainnet) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            chains: {
                                chainId: number;
                                canonical: string;
                                displayName: string;
                                testnet: boolean;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{account}/tokens/{token}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get balance
         * @description Compute the balance of an account for a given chain+token at a specific timestamp (or now). Returns connected balance (visible on-chain via realtimeBalanceOfNow), disconnected balance (claimable GDA/IDA amounts), total balance, available balance (net of deposit), deposit, net flow rate, and an estimated critical-at timestamp if the account is draining.
         */
        get: {
            parameters: {
                query: {
                    chain: string;
                    timestamp?: string;
                };
                header?: never;
                path: {
                    account: string;
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Real-time balance computed via the entry-fold engine */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            connectedBalance: string;
                            connectedNetFlowRate: string;
                            disconnectedBalance: string;
                            totalBalance: string;
                            availableBalance: string;
                            deposit: string;
                            maybeCriticalAt: string | null;
                            timestamp: string;
                        };
                    };
                };
                /** @description Invalid request parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{account}/tokens/{token}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get balance movement entries
         * @description Raw ledger entries showing every balance change. Each entry is a discrete amount change, flow rate change, or deposit change.
         */
        get: {
            parameters: {
                query: {
                    chain: string;
                    counterparty?: string;
                    startTimestamp?: string;
                    endTimestamp?: string;
                    category?: string;
                    entryType?: string;
                    limit?: string;
                    offset?: string;
                    direction?: "asc" | "desc";
                };
                header?: never;
                path: {
                    account: string;
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Raw balance movement entries (bank statement view) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            entries: {
                                serialId: number;
                                timestamp: string;
                                blockNumber: string;
                                logIndex: string;
                                semanticEventType: string;
                                entryType: string;
                                category: string;
                                subAccount: string;
                                deltaAmount: string | null;
                                deltaFlowRate: string | null;
                                counterparty: string | null;
                            }[];
                            total: number;
                        };
                    };
                };
                /** @description Invalid request parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{account}/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discover account tokens
         * @description Find all chain+token pairs where the account has balance-affecting entries.
         */
        get: {
            parameters: {
                query?: {
                    chain?: string;
                    network?: "mainnet" | "testnet" | "all";
                };
                header?: never;
                path: {
                    account: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All tokens the account has interacted with across chains */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            tokens: {
                                chain: string;
                                token: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{account}/tokens/{token}/counterparties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discover counterparties
         * @description Find all addresses the account has interacted with for a given chain+token.
         */
        get: {
            parameters: {
                query: {
                    chain: string;
                };
                header?: never;
                path: {
                    account: string;
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All counterparties the account has interacted with for this token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            counterparties: {
                                address: string;
                                eventCount: number;
                                netAmount: string;
                                netFlowRate: string;
                            }[];
                        };
                    };
                };
                /** @description Invalid request parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{account}/tokens/{token}/balance-snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get balance snapshots
         * @description Compute balance snapshots at evenly-spaced timestamps between start and end. Uses the fold engine for efficient single-pass computation.
         */
        get: {
            parameters: {
                query: {
                    chain: string;
                    startTimestamp: string;
                    endTimestamp?: string;
                    points?: string;
                };
                header?: never;
                path: {
                    account: string;
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Balance at evenly-spaced timestamps for charting */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            points: {
                                timestamp: string;
                                connectedBalance: string;
                                disconnectedBalance: string;
                                deposit: string;
                                totalBalance: string;
                            }[];
                        };
                    };
                };
                /** @description Invalid request parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{account}/tokens/{token}/balance-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get periodic balance report
         * @description Compute a periodic balance report using the entry-fold engine. Each period shows opening/closing balance, net change, and breakdown by category and counterparty. Optional post-fold filters: `category` (comma list) prunes the byCategory breakdown map and by_category CSV rows; `counterparty` (comma list) prunes byCounterparty and by_counterparty CSV rows. IMPORTANT: the global balance fields (openingBalance, closingBalance, netChange, deposit, netFlowRate, gdaConnectedChange, gdaDisconnectedChange, idaConnectedChange, idaDisconnectedChange) are always account-wide totals and are never filtered — only the breakdown maps are affected.
         */
        get: {
            parameters: {
                query: {
                    chain: string;
                    startDate: string;
                    endDate: string;
                    period?: "daily" | "weekly" | "monthly";
                    format?: "json" | "csv";
                    view?: "totals" | "by_counterparty" | "by_category";
                    category?: string;
                    counterparty?: string;
                };
                header?: never;
                path: {
                    account: string;
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Periodic balance report (daily, weekly, or monthly) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            periods: {
                                label: string;
                                startTimestamp: string;
                                endTimestamp: string;
                                openingBalance: string;
                                closingBalance: string;
                                deposit: string;
                                netFlowRate: string;
                                netChange: string;
                                byCategory: {
                                    [key: string]: string;
                                };
                                byCounterparty: {
                                    [key: string]: string;
                                };
                                gdaConnectedChange: string;
                                gdaDisconnectedChange: string;
                                idaConnectedChange: string;
                                idaDisconnectedChange: string;
                            }[];
                        };
                        "text/csv": string;
                    };
                };
                /** @description Invalid request parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{account}/tokens/{token}/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get balance movements
         * @description Pre-computed balance movements: discrete transfers, stream periods, and deposit changes. Stream periods group flow rate changes into single rows with date ranges and crystallized totals. Optionally bounded by `startTimestamp` / `endTimestamp` (unix seconds, both optional, both inclusive). Two filtering modes: balance_movements rows use lifespan-overlap semantics (a row is included when its `[timestamp, endTimestamp]` intersects the requested window; ongoing stream periods with `isOngoing = true` are treated as open-ended; point-in-time rows with `endTimestamp IS NULL` are matched on their single `timestamp`); account_entries rows use point-in-range semantics (included when their single `timestamp` falls within the window). Additional filters: `movementType` (comma list: discrete, stream_period, deposit, instant_distribution), `category` (comma list), `direction` (in|out based on amount sign), `isOngoing` (true|false), `counterparty` (comma list of addresses). All filters propagate to both query sources, `total`, `hasMore`, and CSV output. Invalid parameter values or `endTimestamp < startTimestamp` return 400.
         */
        get: {
            parameters: {
                query: {
                    chain: string;
                    counterparty?: string;
                    limit?: string;
                    offset?: string;
                    sort?: "asc" | "desc";
                    format?: "json" | "csv";
                    startTimestamp?: string;
                    endTimestamp?: string;
                    movementType?: string;
                    category?: string;
                    direction?: "in" | "out";
                    isOngoing?: "true" | "false";
                };
                header?: never;
                path: {
                    account: string;
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pre-computed balance movements (bank statement view) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            movements: {
                                movementType: string;
                                category: string;
                                counterparty: string | null;
                                semanticEventType: string | null;
                                amount: string;
                                flowRate: string | null;
                                lastUpdateTimestamp: string | null;
                                timestamp: string;
                                endTimestamp: string | null;
                                isOngoing: boolean;
                                isDisconnected: boolean;
                            }[];
                            /** @description Total movements across balance_movements + account_entries. Capped at 20002 (10001 per source) when `totalIsCapped` is true — report as e.g. "10,000+" in UIs. */
                            total: number;
                            /** @description True when either underlying COUNT hit the 10001-row cap; `total` is a lower bound. */
                            totalIsCapped: boolean;
                            /** @description True when more rows exist past the returned page (derived from a fetch-one-extra probe, independent of the capped COUNT). */
                            hasMore: boolean;
                        };
                        "text/csv": string;
                    };
                };
                /** @description Invalid request parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
