/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/chains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List configured chains
         * @description Enumerate the configured chains from docs/chain-configs.json for client dropdowns and validation.
         */
        get: {
            parameters: {
                query?: {
                    network?: "mainnet" | "testnet" | "all";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Configured chains, filtered by `network` (defaults to mainnet) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            chains: {
                                chainId: number;
                                canonical: string;
                                displayName: string;
                                testnet: boolean;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{account}/tokens/{token}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get balance
         * @description Compute the balance of an account for a given chain+token at a specific timestamp (or now). Returns connected balance (visible on-chain via realtimeBalanceOfNow), disconnected balance (claimable GDA/IDA amounts), total balance, available balance (net of deposit), deposit, net flow rate, and an estimated critical-at timestamp if the account is draining.
         */
        get: {
            parameters: {
                query: {
                    chain: string;
                    timestamp?: string;
                };
                header?: never;
                path: {
                    account: string;
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Real-time balance computed via the entry-fold engine */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            connectedBalance: string;
                            connectedNetFlowRate: string;
                            disconnectedBalance: string;
                            totalBalance: string;
                            availableBalance: string;
                            deposit: string;
                            maybeCriticalAt: string | null;
                            timestamp: string;
                            /** @description Token metadata resolved from the Superfluid extended token list. `symbol` and `name` are null only for tokens not present in the token list and not reachable via subgraph fallback. */
                            token: {
                                address: string;
                                symbol: string | null;
                                name: string | null;
                                decimals: number;
                            };
                        };
                    };
                };
                /** @description Invalid request parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{account}/tokens/{token}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get balance movement entries
         * @description Raw ledger entries showing every balance change. Each entry is a discrete amount change, flow rate change, or deposit change.
         */
        get: {
            parameters: {
                query: {
                    chain: string;
                    counterparty?: string;
                    startTimestamp?: string;
                    endTimestamp?: string;
                    category?: string;
                    entryType?: string;
                    limit?: string;
                    offset?: string;
                    direction?: "asc" | "desc";
                };
                header?: never;
                path: {
                    account: string;
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Raw balance movement entries (bank statement view) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            entries: {
                                serialId: number;
                                timestamp: string;
                                blockNumber: string;
                                logIndex: string;
                                semanticEventType: string;
                                entryType: string;
                                category: string;
                                subAccount: string;
                                deltaAmount: string | null;
                                deltaFlowRate: string | null;
                                /** @description Counterparty address for this entry, or null for operations with no external counterparty (wraps, unwraps, mints, burns, deposit changes). Lowercase hex address when present. Note: balance-report byCounterparty maps use the sentinel key `__none__` for the same concept. */
                                counterparty: string | null;
                            }[];
                            total: number;
                        };
                    };
                };
                /** @description Invalid request parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{account}/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discover account tokens
         * @description Find all chain+token pairs where the account has balance-affecting entries.
         */
        get: {
            parameters: {
                query?: {
                    chain?: string;
                    network?: "mainnet" | "testnet" | "all";
                };
                header?: never;
                path: {
                    account: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All tokens the account has interacted with across chains */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            tokens: {
                                chain: string;
                                token: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{account}/tokens/{token}/counterparties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discover counterparties
         * @description Find all addresses the account has interacted with for a given chain+token.
         */
        get: {
            parameters: {
                query: {
                    chain: string;
                };
                header?: never;
                path: {
                    account: string;
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All counterparties the account has interacted with for this token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            counterparties: {
                                address: string;
                                eventCount: number;
                                netAmount: string;
                                netFlowRate: string;
                            }[];
                        };
                    };
                };
                /** @description Invalid request parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{account}/tokens/{token}/balance-snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get balance snapshots
         * @description Compute balance snapshots at evenly-spaced timestamps between start and end. Uses the fold engine for efficient single-pass computation.
         */
        get: {
            parameters: {
                query: {
                    chain: string;
                    startTimestamp: string;
                    endTimestamp?: string;
                    points?: string;
                };
                header?: never;
                path: {
                    account: string;
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Balance at evenly-spaced timestamps for charting */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            points: {
                                timestamp: string;
                                connectedBalance: string;
                                disconnectedBalance: string;
                                deposit: string;
                                totalBalance: string;
                            }[];
                        };
                    };
                };
                /** @description Invalid request parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{account}/tokens/{token}/balance-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get periodic balance report
         * @description Compute a periodic balance report using the entry-fold engine. Each period shows opening/closing balance, net change, and breakdown by category and counterparty. By default (`extrapolate=false`) the report is non-speculative: the in-progress period closes at the server's current time and entirely-future periods are omitted; set `extrapolate=true` for a forecast that projects future periods from the current net flow rate. The top-level `generatedAt` is the as-of calculation time; each period carries `calendarEndTimestamp` and `isComplete`. Optional post-fold filters: `category` (comma list) prunes the byCategory breakdown map and by_category CSV rows; `counterparty` (comma list) prunes byCounterparty and by_counterparty CSV rows. IMPORTANT: the global balance fields (openingBalance, closingBalance, netChange, deposit, netFlowRate, gdaConnectedChange, gdaDisconnectedChange, idaConnectedChange, idaDisconnectedChange, openingConnectedBalance, closingConnectedBalance, openingDisconnectedBalance, closingDisconnectedBalance, openingDeposit, closingDeposit, connectedNetChange, disconnectedNetChange) are always account-wide totals and are never filtered — only the breakdown maps are affected. Breakdown-to-netChange invariant: sum(byCategory values) == netChange AND sum(byCounterparty values) == netChange. byCategory includes CFA streaming/discrete, GDA pool member distributions (category 'gda_member'), and IDA subscriber distributions (category 'ida_subscriber'). The gdaConnectedChange, gdaDisconnectedChange, idaConnectedChange, and idaDisconnectedChange fields are informational audit fields showing the connected/disconnected breakdown.
         */
        get: {
            parameters: {
                query: {
                    chain: string;
                    startDate: string;
                    endDate: string;
                    period?: "daily" | "weekly" | "monthly";
                    format?: "json" | "csv";
                    view?: "totals" | "by_counterparty" | "by_category";
                    category?: string;
                    counterparty?: string;
                    counterpartyDetail?: "true" | "false";
                    extrapolate?: "true" | "false";
                };
                header?: never;
                path: {
                    account: string;
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Periodic balance report (daily, weekly, or monthly) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Token metadata resolved from the Superfluid extended token list. `symbol` and `name` are null only for tokens not present in the token list and not reachable via subgraph fallback. */
                            token: {
                                address: string;
                                symbol: string | null;
                                name: string | null;
                                decimals: number;
                            };
                            /** @description The server's request-time clock (unix seconds, UTC) used as the as-of calculation time for clamping the in-progress period. This is the computation cutoff, NOT a response-serialization timestamp. */
                            generatedAt: string;
                            /** @description The effective extrapolation mode applied to this report (after defaulting). false = non-speculative (coverage capped at generatedAt); true = forecast (future periods projected from the current net flow rate). Echoed so clients never infer it. */
                            extrapolate: boolean;
                            /** @description The report's effective horizon (unix seconds): the last period's effective endTimestamp. When extrapolate=false this is min(last calendar end, generatedAt). null when no calendar period is covered (e.g. an entirely-future range with extrapolate=false returns no periods). */
                            coverageEndTimestamp: string | null;
                            periods: {
                                label: string;
                                startTimestamp: string;
                                /** @description Effective close of the period (unix seconds). Equals calendarEndTimestamp for complete periods; for the in-progress period under extrapolate=false it equals generatedAt (< calendarEndTimestamp). */
                                endTimestamp: string;
                                /** @description The period's nominal calendar end (unix seconds) before any clamping — the start of the next day/week/month. Lets clients detect a partial period without re-deriving calendar math. */
                                calendarEndTimestamp: string;
                                /** @description Whether the period's calendar window has fully elapsed (calendarEndTimestamp <= generatedAt). Reflects real calendar completeness independent of extrapolate, so an in-progress period reports false even when extrapolate=true (its closing balance is then a projection). */
                                isComplete: boolean;
                                /** @description Total balance at period start (wei): connected + disconnected. Invariant: openingBalance == openingConnectedBalance + openingDisconnectedBalance. */
                                openingBalance: string;
                                /** @description Total balance at period end (wei): connected + disconnected. Invariant: closingBalance == closingConnectedBalance + closingDisconnectedBalance. */
                                closingBalance: string;
                                /** @description CFA stream deposit (buffer) held at period end (wei). Backward-compatible alias for `closingDeposit`. */
                                deposit: string;
                                /** @description Net CFA flow rate at period end (wei/second, signed). */
                                netFlowRate: string;
                                /** @description Total balance change over the period (wei): closingBalance minus openingBalance. Invariant: netChange == connectedNetChange + disconnectedNetChange. */
                                netChange: string;
                                /** @description Net balance change per event category for this period (wei, signed). Includes CFA streaming (cfa), discrete events (transfer, wrap, unwrap, mint, burn, liquidation), GDA pool member distributions (gda_member), and IDA subscriber distributions (ida_subscriber). Invariant: sum(byCategory values) == netChange. */
                                byCategory: {
                                    [key: string]: string;
                                };
                                /** @description Net balance change per counterparty address for this period (wei, signed). Includes CFA flow counterparties, GDA pool addresses, and IDA publisher addresses. The special key `__none__` represents operations with no external counterparty: wraps, unwraps, mints, and burns. All other keys are lowercase Ethereum addresses. Invariant: sum(byCounterparty values) == netChange. */
                                byCounterparty: {
                                    [key: string]: string;
                                };
                                /** @description Per-counterparty detail (only present when `?counterpartyDetail=true`). openingBalance and closingBalance are cumulative balances for this counterparty at period boundaries, including CFA streaming, GDA pool distributions, and IDA subscriber distributions. `netChange` equals the `byCounterparty` entry for the same key. `flowRate` is the combined CFA + GDA flow rate to/from this counterparty at period close (IDA has no streaming component). */
                                byCounterpartyDetail?: {
                                    [key: string]: {
                                        openingBalance: string;
                                        closingBalance: string;
                                        netChange: string;
                                        flowRate: string;
                                    };
                                };
                                /** @description Informational: net change from connected GDA pool distributions over the period (wei). This value is already included in byCategory under 'gda_member'. */
                                gdaConnectedChange: string;
                                /** @description Informational: net change from disconnected GDA pool distributions over the period (wei). This value is already included in byCategory under 'gda_member'. */
                                gdaDisconnectedChange: string;
                                /** @description Informational: net change from approved IDA subscriber distributions over the period (wei). This value is already included in byCategory under 'ida_subscriber'. */
                                idaConnectedChange: string;
                                /** @description Informational: net change from unapproved IDA subscriber distributions over the period (wei). This value is already included in byCategory under 'ida_subscriber'. */
                                idaDisconnectedChange: string;
                                /** @description Protocol-connected balance at period start (wei). Includes deposit. Equals C_open + P_open + connected GDA member balance + approved IDA subscriber balance. */
                                openingConnectedBalance: string;
                                /** @description Protocol-connected balance at period end (wei). Includes deposit. Equals C_close + P_close + connected GDA member balance + approved IDA subscriber balance. */
                                closingConnectedBalance: string;
                                /** @description Claimable (disconnected) balance at period start (wei). Sum of disconnected GDA pool member balance + unapproved IDA subscriber balance. Zero for accounts with no GDA/IDA activity. */
                                openingDisconnectedBalance: string;
                                /** @description Claimable (disconnected) balance at period end (wei). Sum of disconnected GDA pool member balance + unapproved IDA subscriber balance. Zero for accounts with no GDA/IDA activity. */
                                closingDisconnectedBalance: string;
                                /** @description CFA stream deposit (buffer) held at period start (wei). */
                                openingDeposit: string;
                                /** @description CFA stream deposit (buffer) held at period end (wei). Same value as the `deposit` field (backward-compatible alias). */
                                closingDeposit: string;
                                /** @description Net change in connected balance over the period (wei). Equals closingConnectedBalance minus openingConnectedBalance. Invariant: connectedNetChange + disconnectedNetChange == netChange. */
                                connectedNetChange: string;
                                /** @description Net change in disconnected balance over the period (wei). Equals closingDisconnectedBalance minus openingDisconnectedBalance. Invariant: connectedNetChange + disconnectedNetChange == netChange. */
                                disconnectedNetChange: string;
                            }[];
                        };
                        "text/csv": string;
                    };
                };
                /** @description Invalid request parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{account}/tokens/{token}/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get balance movements
         * @description Pre-computed balance movements: discrete transfers, stream periods, and deposit changes. Stream periods group flow rate changes into single rows with date ranges and crystallized totals. Optionally bounded by `startTimestamp` / `endTimestamp` (unix seconds, both optional, both inclusive). Two filtering modes: balance_movements rows use lifespan-overlap semantics (a row is included when its `[timestamp, endTimestamp]` intersects the requested window; ongoing stream periods with `isOngoing = true` are treated as open-ended; point-in-time rows with `endTimestamp IS NULL` are matched on their single `timestamp`); account_entries rows use point-in-range semantics (included when their single `timestamp` falls within the window). Additional filters: `movementType` (comma list: discrete, stream_period, deposit, instant_distribution), `category` (comma list), `direction` (in|out based on amount sign), `isOngoing` (true|false), `isDisconnected` (true|false), `counterparty` (comma list of addresses). All filters propagate to both query sources, `total`, `hasMore`, and CSV output. Pagination: use `offset` for simple offset-based paging, or `cursor` / `nextCursor` for cursor-based paging (recommended for large result sets). `cursor` and `offset` are mutually exclusive. Invalid parameter values, `endTimestamp < startTimestamp`, or a malformed `cursor` return 400.
         */
        get: {
            parameters: {
                query: {
                    chain: string;
                    counterparty?: string;
                    limit?: string;
                    offset?: string;
                    cursor?: string;
                    sort?: "asc" | "desc";
                    format?: "json" | "csv";
                    startTimestamp?: string;
                    endTimestamp?: string;
                    movementType?: string;
                    category?: string;
                    direction?: "in" | "out";
                    isOngoing?: "true" | "false";
                    isDisconnected?: "true" | "false";
                };
                header?: never;
                path: {
                    account: string;
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pre-computed balance movements (bank statement view) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Token metadata resolved from the Superfluid extended token list. `symbol` and `name` are null only for tokens not present in the token list and not reachable via subgraph fallback. */
                            token: {
                                address: string;
                                symbol: string | null;
                                name: string | null;
                                decimals: number;
                            };
                            movements: {
                                movementType: string;
                                category: string;
                                /** @description Counterparty address for this movement, or null for operations with no external counterparty (wraps, unwraps, mints, burns, deposit changes). Lowercase hex address when present. */
                                counterparty: string | null;
                                semanticEventType: string | null;
                                amount: string;
                                flowRate: string | null;
                                lastUpdateTimestamp: string | null;
                                timestamp: string;
                                endTimestamp: string | null;
                                isOngoing: boolean;
                                isDisconnected: boolean;
                            }[];
                            /** @description Total movements across balance_movements + account_entries. Capped at 20002 (10001 per source) when `totalIsCapped` is true — report as e.g. "10,000+" in UIs. */
                            total: number;
                            /** @description True when either underlying COUNT hit the 10001-row cap; `total` is a lower bound. */
                            totalIsCapped: boolean;
                            /** @description True when more rows exist past the returned page (derived from a fetch-one-extra probe, independent of the capped COUNT). */
                            hasMore: boolean;
                            /** @description Opaque cursor for the next page. Pass as `cursor` in the next request. Null when `hasMore` is false (no more pages) or when using offset-based pagination. To bootstrap cursor pagination, send `?cursor=` (empty string) on the first request. */
                            nextCursor: string | null;
                        };
                        "text/csv": string;
                    };
                };
                /** @description Invalid request parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
