name: Dev CI/CD

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  test_setup:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      netlify_url: ${{ steps.waitForDeployment.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Wait for Netlify
        uses: probablyup/wait-for-netlify-action@3.2.0 # Check the source code before updating version because it uses personal Netlify access token which does not have granular access control.
        id: waitForDeployment
        with:
          site_id: "aa82cf1e-ce5d-432f-99bf-77a0b8c13277"
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}

  test_chrome:
    runs-on: ubuntu-latest
    needs: ["test_setup"]
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress Chrome tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          record: true
          parallel: true
          group: 'test'
          env: STATIC_BALANCE_ACCOUNT_PRIVATE_KEY=${{ secrets.STATIC_BALANCE_ACCOUNT_PRIVATE_KEY }},ONGOING_STREAM_ACCOUNT_PRIVATE_KEY=${{ secrets.ONGOING_STREAM_ACCOUNT_PRIVATE_KEY }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.V2_CYPRESS_RECORD_KEY }}
          CYPRESS_baseUrl: ${{ needs.test_setup.outputs.netlify_url }}
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

  # test_firefox:
  #   runs-on: ubuntu-latest
  #   needs: ["test_setup"]
  #   timeout-minutes: 30
  #   container:
  #     image: cypress/browsers:node14.19.0-chrome100-ff99-edge
  #     options: --user 1001
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       containers: [1, 2]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Cypress Firefox tests
  #       uses: cypress-io/github-action@v4
  #       with:
  #         browser: firefox
  #         record: true
  #         parallel: true
  #         ci-build-id: "${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}"
  #         env: STATIC_BALANCE_ACCOUNT_PRIVATE_KEY=${{ secrets.STATIC_BALANCE_ACCOUNT_PRIVATE_KEY }},ONGOING_STREAM_ACCOUNT_PRIVATE_KEY=${{ secrets.ONGOING_STREAM_ACCOUNT_PRIVATE_KEY }}
  #       env:
  #         CYPRESS_RECORD_KEY: ${{ secrets.V2_CYPRESS_RECORD_KEY }}
  #         CYPRESS_baseUrl: ${{ needs.test_setup.outputs.netlify_url }}
  #         GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
