name: Dev CI/CD

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  test_chrome:
    name: Cypress run
    runs-on: ubuntu-latest
    container: cypress/browsers:latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress Chrome tests
        uses: cypress-io/github-action@v4
        with:
          install: true
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.V2_CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          CYPRESS_BASE_URL: https://deploy-preview-179--superfluid-dashboard.netlify.app/
