name: Dev CI/CD

on:
  push:
    branches-ignore:
      - master

jobs:

  test-setup:
    timeout-minutes: 60
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest
      options: --user 1001
    outputs:
      uuid: ${{ steps.uuid.outputs.value }}

    steps:
      - name: Generate unique ID 💎
        id: uuid
        run: echo "::set-output name=value::sha-$GITHUB_SHA-time-$(date +"%s")"

      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - uses: c-hive/gha-yarn-cache@v2
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Install JS dependencies
        run: yarn install
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Wait for Netlify
        uses: probablyup/wait-for-netlify-action@3.2.0 # Check the source code before updating version because it uses personal Netlify access token which does not have granular access control.
        id: waitForDeployment
        with:
          site_id: "aa82cf1e-ce5d-432f-99bf-77a0b8c13277"
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}

  chrome-tests:
    needs: ["test-setup"]
    timeout-minutes: 60
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest
    strategy:
      fail-fast: false
      matrix:
        container: [ 1,2,3,4,5,6 ]
    steps:
      - name: Cypress tests
        uses: cypress-io/github-action@v4
        with:
          install: false
          browser: chrome
          wait-on: ${{ steps.waitForDeployment.outputs.url }}
          wait-on-timeout: 180
          record: true
          parallel: true
          working-directory: tests
          ci-build-id: ${{ needs.test-setup.outputs.uuid }}
          env: STATIC_BALANCE_ACCOUNT_PRIVATE_KEY=${{ secrets.STATIC_BALANCE_ACCOUNT_PRIVATE_KEY }},ONGOING_STREAM_ACCOUNT_PRIVATE_KEY=${{ secrets.ONGOING_STREAM_ACCOUNT_PRIVATE_KEY }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.V2_CYPRESS_RECORD_KEY }}
          CYPRESS_baseUrl: ${{ steps.waitForDeployment.outputs.url }}
