name: Dev CI/CD

on:
  push:
    branches-ignore:
      - master

jobs:
  test-suites:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.5.0-chrome97-ff96
    strategy:
      fail-fast: false
      matrix:
        container: [1,2,3,4]
    steps:
      - uses: actions/checkout@v2

      - name: Cypress tests
        uses: cypress-io/github-action@v4
        with:
          install: true
          record: true
          parallel: true
          working-directory: tests
          cache-key: "testing2"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.V2_CYPRESS_RECORD_KEY }}
